### ISSUE TITLE
Unable to contact Discord or email

### ISSUE THREAD

**Issue by stormy1777** [ferdium/ferdium-website#37]
Trying to report an issue with regards to Slack dark-theme - not all elements are dark, e.g:

![1675124755905blob](https://user-images.githubusercontent.com/25287044/218427860-4bd04ab4-d6a4-4f29-ae56-885a2acedeb6.png)

having hard time getting in touch for several months it's like that:

support page https://ferdium.org/contact says:

"The easiest way to do this, is by joining our Discord server."  that URL is:

https://discord.gg/xqA9vTP6

clicking results in this notice about "Invalid Invite":

![image](https://user-images.githubusercontent.com/25287044/218425913-64a2a6f8-412a-403a-963b-746c4ce5b651.png)

also on that page it mentions the email: "contact us at [contact@ferdium.org](mailto:contact@ferdium.org)"

that bounces back:

"Sorry, we were unable to deliver your message to the following address.

<[contact@ferdium.org](mailto:contact@ferdium.org)>:
550: 5.1.1 The email account that you tried to reach does not exist. Please try double-checking the recipient's email address for typos or unnecessary spaces. - ImprovMX"

finally decided to open this issue here...

**Comment by Alphrag** [comment]
Hi @stormy1777 sorry about that, I have just seen this issue. If you are still looking for it, a correct discord invitation is as follows: https://discord.com/invite/jVv4Qns8pP (I'll modify the website when I find a second). 
As for the contact email, I'll chase to see why this has not been redirected to any of us.

**Comment by vraravam** [comment]
I have updated the website codebase now. It should publish automatically once the build completes.
